Repository dionisiusch/gp-printing, pull requests merged in 2019-09, with the labels that each got.

#16 [Assets] Change sql db
  assets/sql/gp-printing.sql
Labels: improvement

#17 [Pengerjaan] Fix modal detail pengerjaan
  assets/sql/gp-printing.sql
  controller/pengerjaan/pengerjaan_show.php
  controller/sample/sample_getDetailSample.php
  controller/sample/sample_show.php
Labels: bug

#24 resolve conflict
  controller/pengerjaan/pengerjaan_insertDetailPengerjaan.php
Labels: bug

#28 [Pengerjaan][Sample] Fix Status button
  controller/pengerjaan/pengerjaan_getDetailPengerjaan.php
  controller/pengerjaan/pengerjaan_insertDetailPengerjaan.php
  controller/sample/sample_getDetailSample.php
Labels: improvement

#30 [Pengerjaan] Fix logic insert revisi insertDetailPengerjaan
  controller/pengerjaan/pengerjaan_insertDetailPengerjaan.php
Labels: bug

#38 [Pengerjaan] Add more detail in modal detailpengerjaan if status revisi [detailTransaksi]Delete modul(Temporary)
  controller/pengerjaan/pengerjaan_getDetailPengerjaan.php
  view/header.php
Labels: Delete, improvement

#43 [Revisi] change default "0000-00-00" to null
  controller/revisi/revisi_show.php
Labels: bug

#44 [sample] change id pelanggan to int #40
  controller/sample/sample_add.php
Labels: bug

#46 [sample][pengerjaan][revis]Add button to (module)_show #42
  controller/pengerjaan/pengerjaan_getDetailPengerjaan.php
  controller/pengerjaan/pengerjaan_show.php
  controller/revisi/revisi_getDetailRevisi.php
  controller/revisi/revisi_show.php
  controller/sample/sample_getDetailSample.php
  controller/sample/sample_show.php
Labels: improvement

#50 [pengerjaan][revisi]add validation qty and [pengerjaan][revisi][sample]delete button
  controller/pengerjaan/pengerjaan_delete.php
  controller/pengerjaan/pengerjaan_insertDetailPengerjaan.php
  controller/pengerjaan/pengerjaan_show.php
  controller/revisi/revisi_delete.php
  controller/revisi/revisi_insertDetailRevisi.php
  controller/revisi/revisi_show.php
  controller/sample/sample_delete.php
  controller/sample/sample_show.php
Labels: improvement

#51 [Obat]Add feature Obat (scratch)
  assets/sql/gp-printing.sql
  controller/obat/obat_add.php
  controller/obat/obat_getDetailObat.php
  controller/obat/obat_show.php
  view/header.php
  view/obat.php
Labels: New Create

#55 [gudang]add Gudang(scratch)
  assets/sql/gp-printing.sql
  controller/gudang/gudang_UpdateStatusGudang.php
  controller/gudang/gudang_changeStatus.php
  controller/gudang/gudang_delete.php
  controller/gudang/gudang_getDetailGudang.php
  controller/gudang/gudang_show.php
  view/gudang.php
  view/header.php
Labels: New Create

#59 improve pengerjaan + change db
  assets/sql/gp-printing.sql
  controller/gudang/gudang_show.php
  controller/pengerjaan/pengerjaan_changeStatus.php
  controller/pengerjaan/pengerjaan_getDetailPengerjaan.php
Labels: improvement

#60 [obat][revisi][gudang]update all from obat,revisi and gudang
  assets/sql/gp-printing.sql
  controller/action/autofillFormPengerjaan.php
  controller/fetch/fetch_pengerjaan.php
  controller/fetch/fetch_revisi.php
  controller/gudang/gudang_getDetailGudang.php
  controller/obat/obat_show.php
  controller/pengerjaan/pengerjaan_getAllPengerjaan.php
  controller/revisi/revisi_addPengerjaan.php
  controller/revisi/revisi_addRevisi.php
  controller/revisi/revisi_getAllRevisi.php
  controller/revisi/revisi_getDetailRevisi.php
  controller/revisi/revisi_insertDetailRevisi.php
  controller/revisi/revisi_show.php
  view/revisi.php
Labels: improvement

#61 [Pengerjaan] Refactor flow to gudang and add checkbox & [Pengerjaan] Improve modal show in pengerjaan
  controller/pengerjaan/pengerjaan_changeStatus.php
  controller/pengerjaan/pengerjaan_getDetailPengerjaan.php
  controller/pengerjaan/pengerjaan_insertDetailPengerjaan.php
  controller/pengerjaan/pengerjaan_insertPengerjaan.php
  controller/pengerjaan/pengerjaan_show.php
  controller/sample/sample_changeStatus.php
  controller/sample/sample_insertTglNaikBahan.php
  controller/sample/sample_show.php
Labels: improvement

#63 [Pengerjaan] Insert To gudang
  controller/pengerjaan/pengerjaan_insertDetailPengerjaan.php
Labels: improvement

#67 [Gudang] Improve Gudang #62
  controller/gudang/gudang_show.php
  controller/pengerjaan/pengerjaan_insertDetailPengerjaan.php
  controller/revisi/revisi_insertDetailRevisi.php
Labels: improvement

#74 [Pengerjaan] Add new history masuk ke gudang dari pengerjaan - [Sample][Pengerjaan] Add validation stock obat
  assets/sql/pengerjaan_gudang.sql
  controller/gudang/gudang_getDetailGudang.php
  controller/pengerjaan/pengerjaan_getDetailPengerjaan.php
  controller/pengerjaan/pengerjaan_insertDetailPengerjaan.php
  controller/pengerjaan/pengerjaan_insertPengerjaan.php
  controller/sample/sample_add.php
  controller/sample/sample_changeStatus.php
  controller/sample/sample_insertTglNaikBahan.php
  controller/sample/sample_show.php
Labels: improvement

#77 [Dasboard]Add calender event + notification
  controller/calendar/calendar_getEvent.php
  controller/calendar/index.php
  index.php
Labels: New Create

#80 [sql] add db
  assets/sql/gp-printing.sql
  view/revisi.php
Labels: improvement

#81 [sql]change db
  assets/sql/gp-printing.sql
Labels: improvement

#87 [Posisi] New Menu Posisi (insert,update,delete)
  controller/login/loginsession.php
  controller/posisi/posisi_actionEdit.php
  controller/posisi/posisi_add.php
  controller/posisi/posisi_delete.php
  controller/posisi/posisi_editPosisi.php
  controller/posisi/posisi_show.php
  view/header.php
  view/posisi.php
Labels: New Create

#88 [Gudang]Improve flow ambil barang
  assets/sql/gp-printing.sql
  controller/gudang/gudang_UpdateStatusGudang.php
  controller/gudang/gudang_changeStatus.php
  controller/gudang/gudang_getDetailGudang.php
  controller/gudang/gudang_show.php
  controller/pengerjaan/pengerjaan_insertDetailPengerjaan.php
  controller/revisi/revisi_insertDetailRevisi.php
Labels: improvement

#90 [Dashboard][Sample][Pengerjaan] Change date format - perkiraan biaya
  controller/config/asset.php
  controller/obat/obat_getBiaya.php
  controller/obat/obat_print.php
  controller/pengerjaan/pengerjaan_getDetailPengerjaan.php
  controller/pengerjaan/pengerjaan_insertPengerjaan.php
  controller/sample/sample_add.php
  controller/sample/sample_changeStatus.php
  controller/sample/sample_getDetailSample.php
  view/header.php
  view/sample.php
Labels: improvement

#91 [gudang][revisi]change input type and date
  assets/sql/gp-printing.sql
  controller/gudang/gudang_UpdateStatusGudang.php
  controller/gudang/gudang_changeStatus.php
  controller/gudang/gudang_getDetailGudang.php
  controller/revisi/revisi_getDetailRevisi.php
  controller/revisi/revisi_show.php
  view/header.php
Labels: improvement

#94 [Gudang]add rupiah format
  controller/gudang/gudang_changeStatus.php
Labels: improvement

#95 [Gudang] Add validation ambil barang>stok -[DB] Change linken config db to staging online db
  controller/config/linken.php
  controller/gudang/gudang_UpdateStatusGudang.php
  controller/gudang/gudang_getDetailGudang.php
  controller/gudang/gudang_show.php
  controller/obat/obat_show.php
  controller/pengerjaan/pengerjaan_getDetailPengerjaan.php
  controller/pengerjaan/pengerjaan_insertPengerjaan.php
Labels: improvement
